name: ai_env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.7
  - pip
  - pip:
      - yfinance
