# Price data configuration
price_col: close
volume_col: volume

# Technical indicator parameters
window_sizes: [14, 30, 50, 100, 200]

# Feature normalization
normalization: zscore
normalization_lookback: 252  # One trading year

# Feature selection
features:
  price_based:
    - sma
    - ema
    - bbands
    - atr
  momentum:
    - rsi
    - cci
    - macd
    - stoch
  volume:
    - vwap
    - volume_sma
  trend:
    - adx
  returns:
    - returns
    - log_returns
  volatility:
    - volatility
    - parkinson 