# Training parameters
num_episodes: 1000
window_size: 50
commission: 0.001
start_training_after_steps: 10000
save_interval: 50000
early_stopping_window: 100
target_sharpe: 1.5

# Risk management parameters
risk_params:
  max_position: 1.0
  max_leverage: 1.0
  position_step: 0.1
  max_drawdown: 0.15
  vol_lookback: 20
  vol_target: 0.15
  transaction_cost: 0.001

# Agent parameters
agent_params:
  hidden_dim: 256
  buffer_size: 1000000
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  alpha: 0.2
  learning_rate: 0.0003
  automatic_entropy_tuning: true 