agent_params:
  alpha: 0.2
  automatic_entropy_tuning: true
  batch_size: 256
  buffer_size: 500000
  gamma: 0.99
  gradient_clip: 1.0
  hidden_dim: 128
  learning_rate: 5.0e-05
  tau: 0.005
  use_batch_norm: false
commission: 0.001
env_params:
  reward_scaling: 1.0
  risk_aversion: 0.1
  vol_lookback: 20
num_episodes: 200
save_interval: 10000
window_size: 50
